/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smart_wireless_control;

import com.fazecast.jSerialComm.SerialPort;
import java.io.IOException;
import java.io.OutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author sireg
 */
public class Gui extends javax.swing.JFrame {
    
    //Declare Global Variable
    SerialPort portSerial;
    private OutputStream output = null;
    private static final String PANEL1ON = "A";
    private static final String PANEL1OFF = "B";
    private static final String PANEL2ON = "C";
    private static final String PANEL2OFF = "D";
    private static final String PANEL3ON = "E";
    private static final String PANEL3OFF = "F";
    private static final String PANEL4ON = "G";
    private static final String PANEL4OFF = "H";
    
    private static final int[] Baudrate = {300, 1200, 2400, 4800, 9600, 19200,
                                           38400, 57600, 74880, 115200, 230400,
                                           250000, 500000, 1000000, 2000000};
    
    ImageIcon iconApps;
    

    /**
     * Creates new form Gui
     */
    public Gui() {
        initComponents();
        btnPnl1Off.setVisible(false);
        btnPnl2Off.setVisible(false);
        btnPnl3Off.setVisible(false);
        btnPnl4Off.setVisible(false);
        
        iconApps = new ImageIcon("src/wifi.png");
        setIconImage(iconApps.getImage());
        
        SerialPort[] portName = SerialPort.getCommPorts();
        for (int i=0; i<portName.length; i++){
            cmbPort.addItem(portName[i].getSystemPortName());
        }
        
        for (int j=0; j<Baudrate.length; j++){
            String Baud = Integer.toString(Baudrate[j]);
            cmbBaudrate.addItem(Baud);
        }
    }
    
    public void ConnectionStart(){
        portSerial = SerialPort.getCommPort(cmbPort.getSelectedItem().toString());
        String rate = cmbBaudrate.getSelectedItem().toString();
        int Val = Integer.parseInt(rate);
        portSerial.setBaudRate(Val);
        portSerial.setComPortTimeouts(SerialPort.TIMEOUT_SCANNER, 0, 0);
        
        if(portSerial.openPort()){
            output = portSerial.getOutputStream();
            
        }
    }
    
    private void SendData(String data){
        try {
            output.write(data.getBytes());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error");
        }
    }
    
    private void CloseSerialPort(){
        if(portSerial != null){
            portSerial.closePort();
            JOptionPane.showMessageDialog(this, "Serial Port Closed");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbBaudrate = new javax.swing.JComboBox<>();
        cmbPort = new javax.swing.JComboBox<>();
        btnConnect = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnPnl2On = new javax.swing.JButton();
        btnPnl2Off = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnPnl1On = new javax.swing.JButton();
        btnPnl1Off = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnPnl4On = new javax.swing.JButton();
        btnPnl4Off = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnPnl3On = new javax.swing.JButton();
        btnPnl3Off = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wireless-Based Control Application Using NRF24L01");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Baudrate   :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 80, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Serial Port :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        cmbBaudrate.setBackground(new java.awt.Color(255, 102, 204));
        cmbBaudrate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmbBaudrate.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(cmbBaudrate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 120, 40));

        cmbPort.setBackground(new java.awt.Color(255, 102, 204));
        cmbPort.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmbPort.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(cmbPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 120, 40));

        btnConnect.setBackground(new java.awt.Color(255, 102, 204));
        btnConnect.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnConnect.setForeground(new java.awt.Color(0, 0, 0));
        btnConnect.setText("Connect");
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });
        jPanel1.add(btnConnect, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 120, 40));

        jPanel2.setBackground(new java.awt.Color(255, 102, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Panel Control 2");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        btnPnl2On.setBackground(new java.awt.Color(51, 204, 255));
        btnPnl2On.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnPnl2On.setForeground(new java.awt.Color(0, 0, 0));
        btnPnl2On.setText("ON");
        btnPnl2On.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPnl2On.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPnl2OnActionPerformed(evt);
            }
        });
        jPanel2.add(btnPnl2On, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 60, 30));

        btnPnl2Off.setBackground(new java.awt.Color(51, 204, 255));
        btnPnl2Off.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnPnl2Off.setForeground(new java.awt.Color(0, 0, 0));
        btnPnl2Off.setText("OFF");
        btnPnl2Off.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPnl2Off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPnl2OffActionPerformed(evt);
            }
        });
        jPanel2.add(btnPnl2Off, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 60, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 150, 90));

        jPanel3.setBackground(new java.awt.Color(255, 102, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Panel Control 1");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        btnPnl1On.setBackground(new java.awt.Color(51, 204, 255));
        btnPnl1On.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnPnl1On.setForeground(new java.awt.Color(0, 0, 0));
        btnPnl1On.setText("ON");
        btnPnl1On.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPnl1On.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPnl1OnActionPerformed(evt);
            }
        });
        jPanel3.add(btnPnl1On, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 60, 30));

        btnPnl1Off.setBackground(new java.awt.Color(51, 204, 255));
        btnPnl1Off.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnPnl1Off.setForeground(new java.awt.Color(0, 0, 0));
        btnPnl1Off.setText("OFF");
        btnPnl1Off.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPnl1Off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPnl1OffActionPerformed(evt);
            }
        });
        jPanel3.add(btnPnl1Off, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 60, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 150, 90));

        jPanel4.setBackground(new java.awt.Color(255, 102, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Panel Control 4");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        btnPnl4On.setBackground(new java.awt.Color(51, 204, 255));
        btnPnl4On.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnPnl4On.setForeground(new java.awt.Color(0, 0, 0));
        btnPnl4On.setText("ON");
        btnPnl4On.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPnl4On.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPnl4OnActionPerformed(evt);
            }
        });
        jPanel4.add(btnPnl4On, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 60, 30));

        btnPnl4Off.setBackground(new java.awt.Color(51, 204, 255));
        btnPnl4Off.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnPnl4Off.setForeground(new java.awt.Color(0, 0, 0));
        btnPnl4Off.setText("OFF");
        btnPnl4Off.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPnl4Off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPnl4OffActionPerformed(evt);
            }
        });
        jPanel4.add(btnPnl4Off, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 60, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 150, 90));

        jPanel5.setBackground(new java.awt.Color(255, 102, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Panel Control 3");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        btnPnl3On.setBackground(new java.awt.Color(51, 204, 255));
        btnPnl3On.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnPnl3On.setForeground(new java.awt.Color(0, 0, 0));
        btnPnl3On.setText("ON");
        btnPnl3On.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPnl3On.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPnl3OnActionPerformed(evt);
            }
        });
        jPanel5.add(btnPnl3On, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 60, 30));

        btnPnl3Off.setBackground(new java.awt.Color(51, 204, 255));
        btnPnl3Off.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnPnl3Off.setForeground(new java.awt.Color(0, 0, 0));
        btnPnl3Off.setText("OFF");
        btnPnl3Off.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPnl3Off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPnl3OffActionPerformed(evt);
            }
        });
        jPanel5.add(btnPnl3Off, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 60, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 150, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 230));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
        // TODO add your handling code here:
        if(btnConnect.getText().equals("Connect")){
            btnConnect.setText("Disconnect");
            ConnectionStart();
            JOptionPane.showMessageDialog(this, "Connected");
        }
        else if(btnConnect.getText().equals("Disconnect")){
            btnConnect.setText("Connect");
            CloseSerialPort();
        }
    }//GEN-LAST:event_btnConnectActionPerformed

    private void btnPnl1OnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPnl1OnActionPerformed
        // TODO add your handling code here:
        SendData(PANEL1ON);
        btnPnl1On.setVisible(false);
        btnPnl1Off.setVisible(true);
    }//GEN-LAST:event_btnPnl1OnActionPerformed

    private void btnPnl1OffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPnl1OffActionPerformed
        // TODO add your handling code here:
        SendData(PANEL1OFF);
        btnPnl1On.setVisible(true);
        btnPnl1Off.setVisible(false);
    }//GEN-LAST:event_btnPnl1OffActionPerformed

    private void btnPnl2OnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPnl2OnActionPerformed
        // TODO add your handling code here:
        SendData(PANEL2ON);
        btnPnl2On.setVisible(false);
        btnPnl2Off.setVisible(true);
    }//GEN-LAST:event_btnPnl2OnActionPerformed

    private void btnPnl2OffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPnl2OffActionPerformed
        // TODO add your handling code here:
        SendData(PANEL2OFF);
        btnPnl2On.setVisible(true);
        btnPnl2Off.setVisible(false);
    }//GEN-LAST:event_btnPnl2OffActionPerformed

    private void btnPnl3OnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPnl3OnActionPerformed
        // TODO add your handling code here:
        SendData(PANEL3ON);
        btnPnl3On.setVisible(false);
        btnPnl3Off.setVisible(true);
    }//GEN-LAST:event_btnPnl3OnActionPerformed

    private void btnPnl3OffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPnl3OffActionPerformed
        // TODO add your handling code here:
        SendData(PANEL3OFF);
        btnPnl3On.setVisible(true);
        btnPnl3Off.setVisible(false);
    }//GEN-LAST:event_btnPnl3OffActionPerformed

    private void btnPnl4OnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPnl4OnActionPerformed
        // TODO add your handling code here:
        SendData(PANEL4ON);
        btnPnl4On.setVisible(false);
        btnPnl4Off.setVisible(true);
    }//GEN-LAST:event_btnPnl4OnActionPerformed

    private void btnPnl4OffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPnl4OffActionPerformed
        // TODO add your handling code here:
        SendData(PANEL4OFF);
        btnPnl4On.setVisible(true);
        btnPnl4Off.setVisible(false);
    }//GEN-LAST:event_btnPnl4OffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnPnl1Off;
    private javax.swing.JButton btnPnl1On;
    private javax.swing.JButton btnPnl2Off;
    private javax.swing.JButton btnPnl2On;
    private javax.swing.JButton btnPnl3Off;
    private javax.swing.JButton btnPnl3On;
    private javax.swing.JButton btnPnl4Off;
    private javax.swing.JButton btnPnl4On;
    private javax.swing.JComboBox<String> cmbBaudrate;
    private javax.swing.JComboBox<String> cmbPort;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
